[package]
name = "slicer-toolbox-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["default", "derive"] }
serde_json = "1.0.134"
walkdir = "2.5.0"
anyhow = "1.0.95"