[package]
name = "slicer-toolbox-core"
version = "1.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["default", "derive"] }
serde_json = "1.0.138"
walkdir = "2.5.0"
anyhow = "1.0.95"