name: Rust_Deploy

on: 
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  VCPKG_DEFAULT_TRIPLET: 'x64-windows'
  VCPKG_ROOT: '${{ github.workspace }}/vcpkg'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Version
        run: |
          $content = Get-Content -Path "${{ github.workspace }}/slicer-toolbox-cmd/Cargo.toml" -Raw
          $null = $content -match 'version\s*=\s"(.*)"' 
          echo "VERSION=$($Matches.1)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - uses: lukka/get-cmake@latest
        with:
          useCloudCache: 'true'

      - uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: 'true'
          doNotCache: 'false'
          vcpkgJsonGlob: '**/.deps/vcpkg.json'
          vcpkgGitCommitId: '57c08a3223a1ec03c3a31986ee38d32e90b6039c'

      - name: Integrate
        run: vcpkg integrate install

      - name: Build
        run: cargo build -p slicer-toolbox-cmd --release --target-dir ${{ github.workspace }}/output/

      - uses: ncipollo/release-action@v1
        with:
          tag: "${{ env.VERSION }}.${{ github.run_number }}"
          artifacts: "${{ github.workspace }}/output/*"
          allowUpdates: 'false'
          generateReleaseNotes: 'true'