name: Rust_Deploy

on: 
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Version
      run: | 
        VERSION=$(grep -oP 'version\s*=\s*"\K[^\"]+' ${{ github.workspace }}/slicer-toolbox-cmd/Cargo.toml)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build
      run: cargo build -p slicer-toolbox-cmd --release --target-dir /output

    - uses: ncipollo/release-action@v1
      with:
        tag: "${{ env.VERSION }}"
        artifacts: "/output/*"
        allowUpdates: 'false'
        generateReleaseNotes: 'true'