name: Rust_Deploy

on: 
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Version
      run: |
        $version = Select-String -Path "C:\path\to\your\Cargo.toml" -Pattern 'version\s*=\s*"\K[^\"]+' -AllMatches | ForEach-Object { $_.Matches } | ForEach-Object { $_.Value }
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

    - name: Build
      run: cargo build -p slicer-toolbox-cmd --release --target-dir ${{ github.workspace }}/output/

    - uses: ncipollo/release-action@v1
      with:
        tag: "${{ env.VERSION }}.${{ github.run_number }}"
        artifacts: "${{ github.workspace }}/output/*"
        allowUpdates: 'false'
        generateReleaseNotes: 'true'